language: php
sudo: false
cache:
  directories:
    - $HOME/.npm
branches:
  only:
    - master
php:
  - 7.2

addons:
  ssh_known_hosts: ibaser.com
  apt:
    packages:
      - sshpass
script:
    - npm install --prefix $THEME_ROOT_PATH
    - npm run-script build --prefix $THEME_ROOT_PATH

after_success:
    - rm -rf $THEME_ROOT_PATH/node_modules $THEME_ROOT_PATH/sass
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST < /bin/bash "rm -rf $THEME_PATH_LIVE/ibaser/*"
    - sshpass -e scp -r $THEME_ROOT_PATH/* $DEPLOY_USER@$DEPLOY_HOST:$THEME_PATH_LIVE/ibaser
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST < /bin/bash "wp cache flush --path=$WP_ROOT_LIVE"